services:
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rails_store_api_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY_BASE: a0c96a13723fe0a91e494f88e7afd5d22b76c52abf2d64c1ed448823a38713e7c1c41d19df61cf69021db1413825c7ca5861824d67aacf617fe5a3fcc34fe734

  frontend:
    build:
      context: ../react-store-ui
    ports:
      - "3001:3001"
    volumes:
      - ../react-store-ui:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  pgdata:
